services:
  python_server:
    image: python_server_image:latest
    container_name: python_server
    ports:
      - "4000:4000"
    volumes:
      - ./python_server:/app
    environment:
      - FLASK_ENV=production
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    env_file:
      - .env
    depends_on:
      - redis

  node_server:
    image: node_server_image:latest
    container_name: node_server
    ports:
      - "3003:3003"
    volumes:
      - ./node_server:/app
    environment:
      - NODE_ENV=production
      - PYTHON_SERVER=${PYTHON_SERVER}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - python_server
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis_data: